-- ============================================================
--  SUPABASE (PostgreSQL) - RIFA 3° EMTI
--  Cole TODO este script no SQL Editor do Supabase e clique em "Run"
-- ============================================================

-- ------------------------------------------------------------
--  ADMINISTRADORES (login do painel: celular + senha)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          VARCHAR(100) NOT NULL,
  celular       VARCHAR(20)   NOT NULL,
  senha_hash    VARCHAR(100)  NOT NULL,
  principal     BOOLEAN NOT NULL DEFAULT false,
  criado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),
  CONSTRAINT uq_admins_celular UNIQUE (celular)
);

-- ------------------------------------------------------------
--  CADASTROS (todos os contatos cadastrados no site)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cadastros (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          VARCHAR(150) NOT NULL,
  idade         SMALLINT NULL,
  celular       VARCHAR(20)   NOT NULL,
  senha_hash    VARCHAR(100)  NOT NULL,
  criado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),
  CONSTRAINT uq_cadastros_celular UNIQUE (celular)
);

-- ------------------------------------------------------------
--  RESERVAS (fichas reservadas)
--  status: 'pendente' | 'vendida' | 'liberada'
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reservas (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha         INTEGER NOT NULL,
  id_cadastro   BIGINT NULL,
  nome_cliente  VARCHAR(150) NULL,
  celular_cli   VARCHAR(20) NULL,
  status        TEXT NOT NULL DEFAULT 'pendente',
  data_reserva  TIMESTAMPTZ NOT NULL DEFAULT now(),
  data_venda    TIMESTAMPTZ NULL,
  CONSTRAINT uq_reservas_ficha UNIQUE (ficha),
  CONSTRAINT chk_reservas_status CHECK (status IN ('pendente','vendida','liberada')),
  CONSTRAINT fk_reservas_cadastro FOREIGN KEY (id_cadastro)
    REFERENCES public.cadastros (id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
--  VENDAS CONFIRMADAS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vendas (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha          INTEGER NOT NULL,
  id_cadastro    BIGINT NULL,
  nome_comprador VARCHAR(150) NULL,
  celular_cli    VARCHAR(20) NULL,
  data_pagamento TEXT NULL,
  aprovado_por   BIGINT NULL,
  vendida_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_vendas_ficha UNIQUE (ficha),
  CONSTRAINT fk_vendas_cadastro FOREIGN KEY (id_cadastro)
    REFERENCES public.cadastros (id) ON DELETE SET NULL,
  CONSTRAINT fk_vendas_admin FOREIGN KEY (aprovado_por)
    REFERENCES public.admins (id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
--  LOGINS (registro de todos os logins feitos)
--  tipo: 'usuario' (site) | 'admin' (painel)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logins (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo          TEXT NOT NULL,
  id_cadastro   BIGINT NULL,
  id_admin      BIGINT NULL,
  identificador VARCHAR(20) NULL,
  data_login    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_logins_tipo CHECK (tipo IN ('usuario','admin')),
  CONSTRAINT fk_logins_cadastro FOREIGN KEY (id_cadastro)
    REFERENCES public.cadastros (id) ON DELETE SET NULL,
  CONSTRAINT fk_logins_admin FOREIGN KEY (id_admin)
    REFERENCES public.admins (id) ON DELETE SET NULL
);

-- ------------------------------------------------------------
--  RELATORIOS (registro automático de 2 em 2 dias)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.relatorios (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_registro DATE NOT NULL,
  registrado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_relatorios_data UNIQUE (data_registro)
);

-- ------------------------------------------------------------
--  RIFA STATE (blobs JSON usados pelo site hoje)
--  Cada chave guarda um JSON inteiro (usuarios, reservas,
--  vendidas, vencedora, log, admins...).
--  O site usa esta tabela para sincronizar com o banco.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rifa_state (
  key         TEXT PRIMARY KEY,
  valor       JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.rifa_state DISABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
--  ACESSO (abre para as chaves anon/publishable)
--  Desabilita RLS e concede permissões ao papel anon/authenticated.
--  Pode ser executado quantas vezes quiser (idempotente).
--  IMPORTANTE: para produção, reative RLS com políticas
--  baseadas em autenticação (auth.uid()).
-- ------------------------------------------------------------
ALTER TABLE public.admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cadastros DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logins DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.relatorios DISABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;